use std::{env, fs, path::Path};

/// Single source of truth for the shader params uniform. Order matters:
/// it defines the memory layout on both sides.
const FIELDS: &[&str] = &[
    "sun_height",
    "horizon_y",
    "sun_radius",
    "sun_stripes",
    "grid_speed",
    "grid_scale",
    "glow_strength",
    "star_density",
    "crt_barrel",
    "chroma",
    "exposure",
    "hue_shift",
    "anim_time",
];

fn main() {
    // WebGL2 requires uniform buffer bindings to be 16-byte aligned, so
    // pad the struct to a multiple of four f32s.
    let pad_count = (4 - FIELDS.len() % 4) % 4;
    let padding: Vec<String> = (0..pad_count).map(|i| format!("_pad{i}")).collect();

    let mut wgsl = String::from(
        "// GENERATED by build.rs from its FIELDS list - do not edit.\n\nstruct Params {\n",
    );
    for field in FIELDS.iter().copied().chain(padding.iter().map(String::as_str)) {
        wgsl.push_str(&format!("    {field}: f32,\n"));
    }
    wgsl.push_str("}\n");
    fs::write("assets/shaders/params_gen.wgsl", wgsl).expect("write params_gen.wgsl");

    let mut rs = String::from(
        "/// GENERATED by build.rs from its FIELDS list - do not edit.\n\
         /// The WGSL twin is assets/shaders/params_gen.wgsl.\n\
         #[derive(bevy::render::render_resource::ShaderType, Debug, Clone, Default)]\n\
         pub struct ShaderParams {\n",
    );
    for field in FIELDS.iter().copied().chain(padding.iter().map(String::as_str)) {
        rs.push_str(&format!("    {field}: f32,\n"));
    }
    rs.push_str("}\n");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    fs::write(Path::new(&out_dir).join("shader_params.rs"), rs).expect("write shader_params.rs");

    println!("cargo:rerun-if-changed=build.rs");
}
