// GENERATED by build.rs from its FIELDS list - do not edit.

struct Params {
    sun_height: f32,
    horizon_y: f32,
    sun_radius: f32,
    sun_stripes: f32,
    grid_speed: f32,
    grid_scale: f32,
    glow_strength: f32,
    star_density: f32,
    crt_barrel: f32,
    chroma: f32,
    exposure: f32,
    hue_shift: f32,
    anim_time: f32,
    _pad0: f32,
    _pad1: f32,
    _pad2: f32,
}
