use bevy::prelude::*;

use crate::names;

// ShaderParams: generated by build.rs together with its WGSL twin
// (assets/shaders/params_gen.wgsl) from one field list.
include!(concat!(env!("OUT_DIR"), "/shader_params.rs"));

/// Every tweakable parameter shown in the settings panel.
#[derive(Component, Clone, Copy, PartialEq)]
pub enum Param {
    ScrambleInterval,
    ScrambleDuration,
    NameStyle,
    NameSeparator,
    TimeScale,
    HorizonY,
    SunPosY,
    SunRadius,
    SunStripes,
    GridSpeed,
    GridScale,
    GlowStrength,
    StarDensity,
    CrtBarrel,
    Chroma,
    Exposure,
    HueShift,
    PanelOpacity,
}

impl Param {
    pub const ALL: [Param; 18] = [
        Param::ScrambleInterval,
        Param::ScrambleDuration,
        Param::NameStyle,
        Param::NameSeparator,
        Param::TimeScale,
        Param::HorizonY,
        Param::SunPosY,
        Param::SunRadius,
        Param::SunStripes,
        Param::GridSpeed,
        Param::GridScale,
        Param::GlowStrength,
        Param::StarDensity,
        Param::CrtBarrel,
        Param::Chroma,
        Param::Exposure,
        Param::HueShift,
        Param::PanelOpacity,
    ];

    /// (label, min, max, step)
    pub fn spec(self) -> (&'static str, f32, f32, f32) {
        match self {
            Param::ScrambleInterval => ("scramble interval", 10.0, 500.0, 10.0),
            Param::ScrambleDuration => ("scramble duration", 0.2, 3.0, 0.1),
            Param::NameStyle => ("name style", 0.0, 3.0, 1.0),
            Param::NameSeparator => ("name separator", 0.0, 2.0, 1.0),
            Param::TimeScale => ("time scale", 0.0, 3.0, 0.1),
            Param::HorizonY => ("horizon height", -0.4, 0.3, 0.02),
            Param::SunPosY => ("sun height", 0.0, 0.5, 0.02),
            Param::SunRadius => ("sun radius", 0.05, 0.4, 0.01),
            Param::SunStripes => ("sun stripes", 10.0, 80.0, 5.0),
            Param::GridSpeed => ("grid speed", 0.0, 5.0, 0.2),
            Param::GridScale => ("grid scale", 0.2, 2.0, 0.1),
            Param::GlowStrength => ("horizon glow", 0.0, 2.5, 0.1),
            Param::StarDensity => ("star density", 0.0, 1.5, 0.1),
            Param::CrtBarrel => ("crt barrel", 0.0, 0.4, 0.02),
            Param::Chroma => ("chromatic aberration", 0.0, 0.03, 0.002),
            Param::Exposure => ("exposure", 0.5, 3.0, 0.1),
            Param::HueShift => ("hue shift", 0.0, 6.3, 0.3),
            Param::PanelOpacity => ("panel opacity", 0.2, 1.0, 0.05),
        }
    }
}

/// Tweakable scene parameters, shown in the settings panel.
#[derive(Resource)]
pub struct CustomParams {
    pub scramble_interval_ms: f32,
    pub scramble_duration: f32,
    pub name_style: f32,
    pub name_separator: f32,
    pub time_scale: f32,
    pub horizon_y: f32,
    pub sun_pos_y: f32,
    pub sun_radius: f32,
    pub sun_stripes: f32,
    pub grid_speed: f32,
    pub grid_scale: f32,
    pub glow_strength: f32,
    pub star_density: f32,
    pub crt_barrel: f32,
    pub chroma: f32,
    pub exposure: f32,
    pub hue_shift: f32,
    pub panel_opacity: f32,
}

impl Default for CustomParams {
    fn default() -> Self {
        Self {
            scramble_interval_ms: 20.0,
            scramble_duration: 1.1,
            name_style: 0.0,
            name_separator: 0.0,
            time_scale: 1.0,
            horizon_y: -0.08,
            sun_pos_y: 0.26,
            sun_radius: 0.17,
            sun_stripes: 40.0,
            grid_speed: 1.4,
            grid_scale: 0.7,
            glow_strength: 1.0,
            star_density: 1.0,
            crt_barrel: 0.12,
            chroma: 0.006,
            exposure: 1.5,
            hue_shift: 0.0,
            panel_opacity: 0.85,
        }
    }
}

impl CustomParams {
    fn field(&mut self, param: Param) -> &mut f32 {
        match param {
            Param::ScrambleInterval => &mut self.scramble_interval_ms,
            Param::ScrambleDuration => &mut self.scramble_duration,
            Param::NameStyle => &mut self.name_style,
            Param::NameSeparator => &mut self.name_separator,
            Param::TimeScale => &mut self.time_scale,
            Param::HorizonY => &mut self.horizon_y,
            Param::SunPosY => &mut self.sun_pos_y,
            Param::SunRadius => &mut self.sun_radius,
            Param::SunStripes => &mut self.sun_stripes,
            Param::GridSpeed => &mut self.grid_speed,
            Param::GridScale => &mut self.grid_scale,
            Param::GlowStrength => &mut self.glow_strength,
            Param::StarDensity => &mut self.star_density,
            Param::CrtBarrel => &mut self.crt_barrel,
            Param::Chroma => &mut self.chroma,
            Param::Exposure => &mut self.exposure,
            Param::HueShift => &mut self.hue_shift,
            Param::PanelOpacity => &mut self.panel_opacity,
        }
    }

    pub fn get(&self, param: Param) -> f32 {
        match param {
            Param::ScrambleInterval => self.scramble_interval_ms,
            Param::ScrambleDuration => self.scramble_duration,
            Param::NameStyle => self.name_style,
            Param::NameSeparator => self.name_separator,
            Param::TimeScale => self.time_scale,
            Param::HorizonY => self.horizon_y,
            Param::SunPosY => self.sun_pos_y,
            Param::SunRadius => self.sun_radius,
            Param::SunStripes => self.sun_stripes,
            Param::GridSpeed => self.grid_speed,
            Param::GridScale => self.grid_scale,
            Param::GlowStrength => self.glow_strength,
            Param::StarDensity => self.star_density,
            Param::CrtBarrel => self.crt_barrel,
            Param::Chroma => self.chroma,
            Param::Exposure => self.exposure,
            Param::HueShift => self.hue_shift,
            Param::PanelOpacity => self.panel_opacity,
        }
    }

    pub fn nudge(&mut self, param: Param, direction: f32) {
        let (_, min, max, step) = param.spec();
        let value = self.field(param);
        *value = (*value + step * direction).clamp(min, max);
    }

    /// Human-readable value for the settings panel.
    pub fn display(&self, param: Param) -> String {
        let value = self.get(param);
        match param {
            Param::ScrambleInterval => format!("{} ms", value as u64),
            Param::SunStripes => format!("{}", value as u64),
            Param::NameStyle => names::STYLE_NAMES[value as usize].to_string(),
            Param::NameSeparator => match names::SEPARATORS[value as usize] {
                ' ' => "space".to_string(),
                c => c.to_string(),
            },
            Param::Chroma => format!("{value:.3}"),
            _ => format!("{value:.2}"),
        }
    }

    /// The shader-facing subset of the params.
    pub fn shader_params(&self, anim_time: f32) -> ShaderParams {
        ShaderParams {
            sun_height: self.sun_pos_y,
            horizon_y: self.horizon_y,
            sun_radius: self.sun_radius,
            sun_stripes: self.sun_stripes,
            grid_speed: self.grid_speed,
            grid_scale: self.grid_scale,
            glow_strength: self.glow_strength,
            star_density: self.star_density,
            crt_barrel: self.crt_barrel,
            chroma: self.chroma,
            exposure: self.exposure,
            hue_shift: self.hue_shift,
            anim_time,
            // Padding fields (WebGL2 16-byte size rule) stay zero.
            ..Default::default()
        }
    }
}
